version: "3.2"

services: 

  redis:
    image: "redis:alpine"

    command: redis-server --requirepass user

    ports:
    - "6379:6379"

    volumes:
    - $PWD/redis-data:/var/lib/redis

    container_name: myredis
