apiVersion: apps/v1
kind: Deployment
metadata:
  name: recom-app-deployment
  labels:
    app: recom-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recom-app
  template:
    metadata:
      labels:
        app: recom-app
    spec:
      containers:
      - name: my-flask
        image: brianrepo/myflask:ver2.1
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: recom-app-service
spec:
  type: LoadBalancer
  selector:
    app: recom-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

